// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cggm
Rcpp::List cggm(const arma::mat& W_keys, const arma::vec& W_values, const arma::mat& W_lassoi, const arma::mat& Ri, const arma::vec& Ai, const arma::ivec& pi, const arma::ivec& ui, const arma::mat& S, const arma::vec& lambdas, double lambda_lasso, double eps_lasso, double eps_fusions, double scale_factor_cpath, double scale_factor_lasso, double gss_tol, double conv_tol, int max_iter, bool store_all_res, bool refit, const arma::imat& refit_lasso, int verbose);
RcppExport SEXP _clusterGGM_cggm(SEXP W_keysSEXP, SEXP W_valuesSEXP, SEXP W_lassoiSEXP, SEXP RiSEXP, SEXP AiSEXP, SEXP piSEXP, SEXP uiSEXP, SEXP SSEXP, SEXP lambdasSEXP, SEXP lambda_lassoSEXP, SEXP eps_lassoSEXP, SEXP eps_fusionsSEXP, SEXP scale_factor_cpathSEXP, SEXP scale_factor_lassoSEXP, SEXP gss_tolSEXP, SEXP conv_tolSEXP, SEXP max_iterSEXP, SEXP store_all_resSEXP, SEXP refitSEXP, SEXP refit_lassoSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W_keys(W_keysSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W_values(W_valuesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W_lassoi(W_lassoiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ri(RiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Ai(AiSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ui(uiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_lasso(lambda_lassoSEXP);
    Rcpp::traits::input_parameter< double >::type eps_lasso(eps_lassoSEXP);
    Rcpp::traits::input_parameter< double >::type eps_fusions(eps_fusionsSEXP);
    Rcpp::traits::input_parameter< double >::type scale_factor_cpath(scale_factor_cpathSEXP);
    Rcpp::traits::input_parameter< double >::type scale_factor_lasso(scale_factor_lassoSEXP);
    Rcpp::traits::input_parameter< double >::type gss_tol(gss_tolSEXP);
    Rcpp::traits::input_parameter< double >::type conv_tol(conv_tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type store_all_res(store_all_resSEXP);
    Rcpp::traits::input_parameter< bool >::type refit(refitSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type refit_lasso(refit_lassoSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cggm(W_keys, W_values, W_lassoi, Ri, Ai, pi, ui, S, lambdas, lambda_lasso, eps_lasso, eps_fusions, scale_factor_cpath, scale_factor_lasso, gss_tol, conv_tol, max_iter, store_all_res, refit, refit_lasso, verbose));
    return rcpp_result_gen;
END_RCPP
}
// count_clusters
int count_clusters(const arma::imat& E, int n);
RcppExport SEXP _clusterGGM_count_clusters(SEXP ESEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type E(ESEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(count_clusters(E, n));
    return rcpp_result_gen;
END_RCPP
}
// find_subgraphs
Rcpp::IntegerVector find_subgraphs(const arma::imat& E, int n);
RcppExport SEXP _clusterGGM_find_subgraphs(SEXP ESEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type E(ESEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(find_subgraphs(E, n));
    return rcpp_result_gen;
END_RCPP
}
// find_mst
arma::imat find_mst(const arma::mat& G);
RcppExport SEXP _clusterGGM_find_mst(SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(find_mst(G));
    return rcpp_result_gen;
END_RCPP
}
// median_distance
double median_distance(const arma::mat& Theta);
RcppExport SEXP _clusterGGM_median_distance(SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(median_distance(Theta));
    return rcpp_result_gen;
END_RCPP
}
// k_largest
Rcpp::IntegerVector k_largest(const arma::vec& vec, int k);
RcppExport SEXP _clusterGGM_k_largest(SEXP vecSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(k_largest(vec, k));
    return rcpp_result_gen;
END_RCPP
}
// compute_Theta
arma::mat compute_Theta(const arma::mat& R, const arma::vec& A, const arma::ivec& u);
RcppExport SEXP _clusterGGM_compute_Theta(SEXP RSEXP, SEXP ASEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Theta(R, A, u));
    return rcpp_result_gen;
END_RCPP
}
// update_inverse
arma::mat update_inverse(const arma::mat& M_inv, const arma::mat& M, int k);
RcppExport SEXP _clusterGGM_update_inverse(SEXP M_invSEXP, SEXP MSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M_inv(M_invSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(update_inverse(M_inv, M, k));
    return rcpp_result_gen;
END_RCPP
}
// scaled_squared_norms
arma::mat scaled_squared_norms(const arma::mat& Theta);
RcppExport SEXP _clusterGGM_scaled_squared_norms(SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(scaled_squared_norms(Theta));
    return rcpp_result_gen;
END_RCPP
}
// squared_norms
arma::mat squared_norms(const arma::mat& Theta);
RcppExport SEXP _clusterGGM_squared_norms(SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(squared_norms(Theta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clusterGGM_cggm", (DL_FUNC) &_clusterGGM_cggm, 21},
    {"_clusterGGM_count_clusters", (DL_FUNC) &_clusterGGM_count_clusters, 2},
    {"_clusterGGM_find_subgraphs", (DL_FUNC) &_clusterGGM_find_subgraphs, 2},
    {"_clusterGGM_find_mst", (DL_FUNC) &_clusterGGM_find_mst, 1},
    {"_clusterGGM_median_distance", (DL_FUNC) &_clusterGGM_median_distance, 1},
    {"_clusterGGM_k_largest", (DL_FUNC) &_clusterGGM_k_largest, 2},
    {"_clusterGGM_compute_Theta", (DL_FUNC) &_clusterGGM_compute_Theta, 3},
    {"_clusterGGM_update_inverse", (DL_FUNC) &_clusterGGM_update_inverse, 3},
    {"_clusterGGM_scaled_squared_norms", (DL_FUNC) &_clusterGGM_scaled_squared_norms, 1},
    {"_clusterGGM_squared_norms", (DL_FUNC) &_clusterGGM_squared_norms, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_clusterGGM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
