# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cggm <- function(Ri, Ai, pi, ui, S, UWUi, lambdas, gss_tol, conv_tol, fusion_check_threshold, max_iter, store_all_res, fusion_type, Newton_dd, print_profile_report, verbose) {
    .Call(`_CGGMR_cggm`, Ri, Ai, pi, ui, S, UWUi, lambdas, gss_tol, conv_tol, fusion_check_threshold, max_iter, store_all_res, fusion_type, Newton_dd, print_profile_report, verbose)
}

gradient <- function(R, A, p, u, R_star_0_inv, S, UWU, lambda_cpath, k, fuse_candidate) {
    .Call(`_CGGMR_gradient`, R, A, p, u, R_star_0_inv, S, UWU, lambda_cpath, k, fuse_candidate)
}

hessian <- function(R, A, p, u, R_star_0_inv, S, UWU, lambda, k) {
    .Call(`_CGGMR_hessian`, R, A, p, u, R_star_0_inv, S, UWU, lambda, k)
}

lossRAk <- function(R, A, p, u, R_star_0_inv, S, UWU, lambda_cpath, k) {
    .Call(`_CGGMR_lossRAk`, R, A, p, u, R_star_0_inv, S, UWU, lambda_cpath, k)
}

lossRA <- function(R, A, p, u, S, UWU, lambda_cpath) {
    .Call(`_CGGMR_lossRA`, R, A, p, u, S, UWU, lambda_cpath)
}

.medianDistance <- function(Theta) {
    .Call(`_CGGMR_medianDistance`, Theta)
}

normTheta <- function(Theta, i, j) {
    .Call(`_CGGMR_normTheta`, Theta, i, j)
}

normRA <- function(R, A, p, i, j) {
    .Call(`_CGGMR_normRA`, R, A, p, i, j)
}

.kLargest <- function(vec, k) {
    .Call(`_CGGMR_kLargest`, vec, k)
}

maxStepSize <- function(R, A, p, R_star_0_inv, g, k) {
    .Call(`_CGGMR_maxStepSize`, R, A, p, R_star_0_inv, g, k)
}

gssStepSize <- function(R, A, p, u, R_star_0_inv, S, UWU, g, lambda_cpath, k, a, b, tol) {
    .Call(`_CGGMR_gssStepSize`, R, A, p, u, R_star_0_inv, S, UWU, g, lambda_cpath, k, a, b, tol)
}

updateInverse <- function(inverse, vec, i) {
    .Call(`_CGGMR_updateInverse`, inverse, vec, i)
}

computeRStar0Inv <- function(R, A, p, k) {
    .Call(`_CGGMR_computeRStar0Inv`, R, A, p, k)
}

computeTheta <- function(R, A, u) {
    .Call(`_CGGMR_computeTheta`, R, A, u)
}

.weightsTheta <- function(Theta, phi) {
    .Call(`_CGGMR_weightsTheta`, Theta, phi)
}

